# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "96fafb6e4a063474e5073e42e9b556f6"
name = "logs"
handle = "logs-2"
application_url = "https://vhs-reunion-subsequently-andrew.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-75a712f6.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://vhs-reunion-subsequently-andrew.trycloudflare.com/auth/callback",
  "https://vhs-reunion-subsequently-andrew.trycloudflare.com/auth/shopify/callback",
  "https://vhs-reunion-subsequently-andrew.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled", "products/update" ]
  uri = "/webhooks"

[pos]
embedded = false
